from fastapi import APIRouter
from app.api.v1.endpoints import auth, users, templates, pages, media, leads, analytics, campaigns, client_notes, campaign_tasks, notifications, activities, client_services, client_tasks, service_roles, workflows, appointments, calendar, invoices, portal, quotations

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(templates.router, prefix="/templates", tags=["templates"])
api_router.include_router(pages.router, prefix="/pages", tags=["landing_pages"])
api_router.include_router(media.router, prefix="/media", tags=["media"])
api_router.include_router(leads.router, prefix="/leads", tags=["leads"])
api_router.include_router(analytics.router, prefix="/analytics", tags=["analytics"])
api_router.include_router(campaigns.router, prefix="/campaigns", tags=["campaigns"])
api_router.include_router(client_notes.router, prefix="/client-notes", tags=["client_notes"])
api_router.include_router(campaign_tasks.router, prefix="/campaign-tasks", tags=["campaign_tasks"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(activities.router, prefix="/activities", tags=["activities"])
api_router.include_router(client_services.router, prefix="/client-services", tags=["client_services"])
api_router.include_router(client_tasks.router, prefix="/client-tasks", tags=["client_tasks"])
api_router.include_router(service_roles.router, prefix="/service-roles", tags=["service_roles"])
api_router.include_router(workflows.router, prefix="/workflows", tags=["workflows"])
api_router.include_router(appointments.router, prefix="/appointments", tags=["appointments"])
api_router.include_router(calendar.router, prefix="/calendar", tags=["calendar"])
api_router.include_router(invoices.router, prefix="/invoices", tags=["invoices"])
api_router.include_router(portal.router, prefix="/portal", tags=["portal"])
api_router.include_router(quotations.router, prefix="/quotations", tags=["quotations"])
